version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: spybot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spybot-app
    depends_on:
      - mongodb
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGODB_URL=mongodb://mongodb:27017/
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
    name: spybot_mongodb_data